title = "Daniel Sada Caraveo | Developer Productivity & Culture"
baseURL = "https://danielsada.tech"
tags = ["portfolio", "developer", "blog", "danielsada", "tec de monterrey", "microsoft"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
ignoreLogs = ['warning-goldmark-raw-html']
[serivces]
    [GoogleAnalytics]
        ID = "UA-43424010-8"
    [Discus]
        Shortname = "danielsada" 
[taxonomies]
    categoria            = 'categorias'
    category            = 'categories'
    tags            = 'tags'
    etiqueta            = 'etiquetas'
    series            = 'series'

[permalinks]
  post = "/:title/"
  categories =  "/:section/:slug"
  
[Params]
    ajaxFormspree = true
    tagline = "Developer Productivity & Culture"
    author = "Daniel Sada"
    description = "Software Development Engineer, I work on sync technologies and storage solutions for services that have millions of users. I empower people to be more productive."
    logoBig = "/images/DanielSadaLogo.png"
    logoSmall = "/images/DanielSadaLogo.png"
    favicon = "/favicon.ico"
    opengraphImage = "/images/DanielSadaLogo.png"
    twitter = "danielsadac"
    linkedin = "danielsadac"
    github = "danielsada"
    facebook = "danielsada"
    email = "hello@danielsada.tech"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
    color = "#aaff00"
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Notas"
    url  = "/#notas"
    weight = 4
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 5


[related]
  includeNewer = false
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'date'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 100



[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  
