title = "Daniel Sada Caraveo | Sync, Notes & Culture"
baseURL = "https://danielsada.tech"
tags = ["portfolio", "developer", "blog", "danielsada", "tec de monterrey", "microsoft"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-43424010-8"
disqusShortname = "danielsada"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[permalinks]
  post = "/:title/"

[Params]
    ajaxFormspree = true
    tagline = "Sync, Notes & Culture"
    author = "Daniel Sada"
    description = "Software Development Engineer, I work on sync technologies and storage solutions for services that have millions of users. I empower people to be more productive."
    logoBig = "/images/DanielSadaLogo.png"
    logoSmall = "/images/DanielSadaLogo.png"
    favicon = "/favicon.ico"
    opengraphImage = "/images/DanielSadaLogo.png"
    twitter = "danielsadac"
    linkedin = "danielsadac"
    github = "danielsada"
    facebook = "danielsada"
    email = "hello@danielsada.tech"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
    color = "#aaff00"
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Notas"
    url  = "/#notas"
    weight = 3
[[menu.main]]
    name = "Reviews"
    url  = "/reviews"
    weight = 4
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 5
